### ISSUE TITLE
NPM publish

### ISSUE THREAD

**Issue by ykornilov** [menvia/node-red-contrib-jenkins#4]
Thank you for your work! Would you check the publication on the npm?
I have worked variant if I make "git clone..." and wrong variant if - "npm i.."

**Comment by felipeplets** [comment]
Hello @ykornilov, thanks for letting us know. This is just a side project still on the first steps, I just synced things up but maybe some issues arise from that. Please let us know if you find any major issue using it and be welcome to collaborate with PRs or raising issues. 

All the best, 
Plets
